### PR TITLE
Update Max Version to Support Komodo 8

### PR DESCRIPTION
**Pull request by tclancy**
To be honest, I did no testing to make sure this works, mainly because I'm not sure how to build the extension/ install locally. Also, I just installed v8 and it seems crashy enough on its own I'm not sure how I'd tell if this was compatible or not.

### CODE REVIEW

**Comment by agroszer** [comment]
That's not enough: http://support.activestate.com/node/9517

**Comment by tclancy** [comment]
Ah thanks, I didn't see that in a quick search. I've subscribed to it and I'll create a new request if I figure it out.

**Comment by raymondbutcher** [comment]
I'll see if I can try out version 8 on the weekend and maybe figure this out. That traceback doesn't look very helpful though!

**Comment by tclancy** [comment]
No, the search results I found for the first bit of the error message suggest it's a pretty general error message for extension errors: https://www.google.com/search?q=koLintService%3A+Unexpected+error+while+linting&aq=f&oq=koLintService%3A+Unexpected+error+while+linting&aqs=chrome.0.57j58&sourceid=chrome&ie=UTF-8#hl=en&q=koLintService:++site:community.activestate.com+Unexpected+error+while+linting&sa=X&ei=zLk4UcmWK_Lx0wGBsYCgAg&ved=0CEEQrQIwAA&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.&bvm=bv.43287494,d.dmQ&fp=cb8d1a9726c4b93c&biw=1920&bih=1056

**Comment by raymondbutcher** [comment]
Unfortunately I have not solved this yet, but I did add some log statements into Komodo and get something somewhat useful:

> Internal Error creating a linter with CID '@rbutcher.com/perfectpython;1': 2147746132 (No such component '@rbutcher.com/perfectpython;1')

The relevant pieces of code are:

**Komodo Edit 8.app/Contents/MacOS/components/koLintService.py**

``` python
    def _getLinterByCID(self, linterCID):
        if linterCID not in self._linterCache:
            try:
                if linterCID.startswith(self.GENERIC_LINTER_AGGREGATOR_CID):
                    languageName = linterCID[len(self.GENERIC_LINTER_AGGREGATOR_CID) + 1:]
                    linter = components.classes[self.GENERIC_LINTER_AGGREGATOR_CID].createInstance(components.interfaces.koILinter)
                    UnwrapObject(linter).initialize(languageName, self)
                elif linterCID not in components.classes.keys():
                    linter = None
                else:
                    linter = components.classes[linterCID].createInstance(components.interfaces.koILinter)
            except COMException, ex:
                errmsg = "Internal Error creating a linter with CID '%s': %s"\
                    % (linterCID, ex)
                raise ServerException(nsError.NS_ERROR_UNEXPECTED, errmsg)
            self._linterCache[linterCID] = linter
```

**Komodo Edit 8.app/Contents/MacOS/python/xpcom/components.py**

``` python
    def createInstance(self, iid = None):
        import xpcom.client
        try:
            return xpcom.client.Component(self.contractid, _get_good_iid(iid))
        except xpcom.COMException, details:
            import nsError
            # Handle "no such component" in a cleaner way for the user.
            if details.errno == nsError.NS_ERROR_FACTORY_NOT_REGISTERED:
                raise xpcom.COMException(details.errno, "No such component '%s'" % (self.contractid,))
            raise # Any other exception reraise.
```

I don't know what it means, but it's a start. I'll keep digging later.

**Comment by agroszer** [comment]
"No such component" that smells like your class PerfectPythonLinter does not get registered
Let's see whether the experts show up: http://community.activestate.com/node/9517#comment-24725

**Comment by toddw-as** [comment]
A quick look showed that 'getProxiedEffectivePrefs' does not exist in Komodo 8 (thanks to me - and I forgot to add a deprecation method), which got replaced with "request.prefset".

The below diff gets PerfectPython working for me on Komodo 8. You'll have to do some more work (try/catch) if you want to support both 7 and 8.

Cheers,
Todd

``` diff
Index: /home/toddw/src/komodo/extensions/perfectpython/pylib/pplinter/preferences.py
index c1bd0b0..026fb30 100644
--- a/pylib/pplinter/preferences.py
+++ b/pylib/pplinter/preferences.py
@@ -1,8 +1,5 @@
 import logging

-from koLintResult import getProxiedEffectivePrefs
-
-
 LOG = logging.getLogger('perfectpython')

 # Ensure that this matches preferences.js and has no '.' characters in it.
@@ -21,7 +18,7 @@ DEFAULTS = {
 class PrefSet(object):

     def __init__(self, request, scope):
-        self.prefset = getProxiedEffectivePrefs(request)
+        self.prefset = request.prefset
         self.scope = scope

     def _get_preference(self, getter, name, scope):
```

**Comment by agroszer** [comment]
Fixed and tested in my fork. All changes are in the pull request. Please merge and release :-)

**Comment by raymondbutcher** [comment]
Thank you all. That fix worked, and has been released along with a bunch of other changes thanks to agroszer. I might switch to Komodo 8 now!

**Pull request closed without merging**
